### GET https://www.jetbrains.com/updates/updates.xml
GET https://www.jetbrains.com/updates/updates.xml

### https://data.services.jetbrains.com/products/releases?code=IC
GET https://data.services.jetbrains.com/products/releases?code=IC

####
GET http://localhost:8080/

####
GET http://localhost:8080/status

####
POST http://localhost:8080/refresh

### http://localhost:8080/refresh/IC
POST http://localhost:8080/refresh/IC
