### GET https://www.jetbrains.com/updates/updates.xml
GET https://www.jetbrains.com/updates/updates.xml

### https://data.services.jetbrains.com/products/releases?code=IC
GET https://data.services.jetbrains.com/products/releases?code=IC

### https://data.services.jetbrains.com/products/releases?code=GW
GET https://data.services.jetbrains.com/products/releases?code=GW

####
GET http://localhost:8080/

####
GET http://localhost:8080/status

####
POST http://localhost:8080/refresh

### /refresh/IC
POST http://localhost:8080/refresh/IC

### /refresh/GW
POST http://localhost:8080/refresh/GW

### /GW
GET http://localhost:8080/GW

### /GW/213.6777.25
GET http://localhost:8080/GW/213.6777.25
