version: '3.8'
services:
  product-info-service-db:
    container_name: product-info-service-db
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgresql
    restart: always
  product-info-service-runner:
    depends_on:
      - product-info-service-db
    image: mbllllb/product-info-service-runner
    ports:
      - "8080-8081:8080"
    environment:
      - DB_PASSWORD=password
      - DB_USER=postgres
      - DB_URI=product-info-service-db:5432/${POSTGRES_DB}
    restart: always
    deploy:
      mode: replicated
      replicas: 2
