version: '3.8'
services:
  product-info-service-db:
    container_name: product-info-service-db
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=productinfoservice
    restart: always
