server:
  shutdown: graceful

spring:
  codec:
    max-in-memory-size: 1MB
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_DB_URI}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  liquibase:
    url: jdbc:postgresql://${POSTGRES_DB_URI}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
