spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/authservice
    username: postgres
    password: password
  liquibase:
    url: jdbc:postgresql://localhost:5433/authservice
    user: postgres
    password: password
