server:
  shutdown: graceful

spring:
  codec:
    max-in-memory-size: 1MB
  lifecycle:
    timeout-per-shutdown-phase: 1m
  r2dbc:
    url: r2dbc:postgresql://${DB_URI}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  liquibase:
    url: jdbc:postgresql://${DB_URI}
    user: ${DB_USER}
    password: ${DB_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: '*'
springdoc:
  show-actuator: true
